spring:
  application:
    name: consumer-service-0
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 5001
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.1:8761/eureka/            