server:
  port: 4001
db:
  user: root
  password: 123456
  url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
  driverClassName: com.mysql.jdbc.Driver
management:
  endpoints:
    enabled-by-default: true
    beans:
      enabled: true
    health:
      show-details: never
  server:
    port: 4002