spring:
  application:
    name: provider-service-0
server:
  port: 6001    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.1:8761/eureka/
  instance:
    hostname: provider-0